#!/bin/sh -eu
#
# Creates PR (GitLab: MR) from the current branch to remote main branch.
# Supports: BitBucket, GitHub, GitLab
#
# You may want to add this to your ~/.gitconfig; this will allow to invoke this
# script by running just 'git pr' in your Git repository:
#
#   [alias]
#   pr = '!/path/to/git-create-pr'
#
# Requires: git, grep, sed, which, x-www-browser
#
# License: MIT

# Detect main branch
main_branch=$(git branch --list --remote origin/main origin/master | head -1 | sed 's,^ *origin/,,')

# Detect current barnch
this_branch=$(git symbolic-ref --short HEAD)
if [ "$this_branch" = "$main_branch" ]; then
    echo "[ERROR] Current branch is $main_branch; cannot create pull request from $this_branch to $main_branch." >&2
    exit 1
fi

# Detect remote and build pull request creation URL
git_remote=$(git remote get-url origin)
case "$git_remote" in
*@bitbucket.org:*)
    echo "[DEBUG] Detected Bitbucket remote: $git_remote" >&2
    create_pr_url=$(echo "$git_remote" | sed 's,:,/,;s,^.*@,https://,;s,.git$,/pull-requests/new,')
    ;;
*@github.com:*)
    echo "[DEBUG] Detected GitHub remote: $git_remote" >&2
    create_pr_url=$(echo "$git_remote" | sed 's,:,/,;s,^git@,https://,;s,.git$,/compare,')"/$main_branch...$this_branch?expand=1"
    ;;
*@gitlab.com:*)
    echo "[DEBUG] Detected GitLab remote: $git_remote" >&2
    create_pr_url=$(echo "$git_remote" | sed 's,:,/,;s,^git@,https://,;s,.git$,/merge_requests/new,')"?merge_request%5Bsource_branch%5D=$this_branch"
    ;;
*)
    echo "[ERROR] Unsupported remote type: $git_remote" >&2
    echo "Supported remote types are: BitBucket, GitHub, GitLab" >&2
    exit 1
    ;;
esac

# Open web browser to create pull request
os=$(uname)
case "$os" in
Darwin)
    open "$create_pr_url"
    ;;
*)
    if command -v x-www-browser > /dev/null; then
        x-www-browser --new-window "$create_pr_url"
    else
        echo "[WARNING] x-www-browser not found" >&2
        echo "Navigate to this URL to create the PR:"
        echo ""
        echo "  $create_pr_url"
        echo ""
    fi
    ;;
esac
